version: "3.9"

networks:
  dev:
    driver: bridge

services:

  client:
    container_name: "client"
    build:
      context: .
      dockerfile: config/Dockerfile
    restart: always
    ports:
      - "3000"
    networks:
      - dev

  server:
    container_name: "server"
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - client
    networks:
      - dev