version: "3.9"

networks:
  dev:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:

services:
  client:
    container_name: "client"
    build:
      context: .
      dockerfile: config/Dockerfile
    networks:
      dev:
    ports:
      - "3000"

  server:
    container_name: "server"
    image: nginx:alpine
    restart: unless-stopped
    networks:
      dev:
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    networks:
      dev:
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
