import type { AppProps } from "next/app"
import { Hydrate, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import Head from "next/head"
import { createGlobalStyle, ThemeProvider } from "styled-components"

import { queryClient, theme } from "@core"

import Layout from "@layout"

const GlobalStyle = createGlobalStyle`  
  html, body, #__next {
    height: 100%;
    margin: 0;
    transition: all 0.2s ease;
    background-color: ${({ theme }) => theme.background};
    font-family: ${({ theme }) => theme.font.name}, sans-serif;
  }

  * {
    outline: none;
  }
`

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Андей Субботин - Портфолио</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logos/favicon.png" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Hydrate state={pageProps.dehydratedState}>
          <ReactQueryDevtools initialIsOpen={false} />
          <ThemeProvider theme={theme}>
            <GlobalStyle />
            <Layout>
              <Component {...pageProps} />
            </Layout>
          </ThemeProvider>
        </Hydrate>
      </QueryClientProvider>
    </>
  )
}

export default App
